### ISSUE TITLE
Takedown page of "Clearingstelle Urheberrecht im Internet"

### ISSUE THREAD

**Issue by cweiske** [Linuzifer/domain_seizure#8]
Maybe you want to add it: https://notice.cuii.info/

**Comment by ghost** [comment]
I just created a pull request requesting for them to add it.

**Comment by Linuzifer** [comment]
Not really a takedown site, as they "only" mess with your DNS, but here you go:
dc0eabc97868ff5e9e3da965349a3206e227f06c
